"""adicionando empresa no model de processo

Revision ID: 0129575516e5
Revises: cf76ec630285
Create Date: 2021-02-28 18:54:24.051334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0129575516e5'
down_revision = 'cf76ec630285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processos', sa.Column('empresa', sa.String(length=40), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processos', 'empresa')
    # ### end Alembic commands ###
