"""update models add confirmation flags

Revision ID: cf76ec630285
Revises: 
Create Date: 2021-02-20 18:23:52.252761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf76ec630285'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etapas', sa.Column('is_finished', sa.Boolean(), nullable=False))
    op.add_column('processos', sa.Column('is_finished', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    op.drop_column('processos', 'is_finished')
    op.drop_column('etapas', 'is_finished')
    # ### end Alembic commands ###
